spin_manifest_version = 2

[application]
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-world"

[component.hello-world]
source = "target/hello-world.wasm"
exclude_files = ["**/node_modules"]
[component.hello-world.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]