spin_manifest_version = 2

[application]
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-world-webpack"

[component.hello-world-webpack]
source = "dist/webpack/hello-world.wasm"
exclude_files = ["**/node_modules"]
[component.hello-world-webpack.build]
command = "npm run build-webpack"
watch = ["src/**/*.ts", "package.json"]